import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "../paths";
import { lanAddress } from "./server";

/**
 * A self-signed certificate for web mode's HTTPS listener.
 *
 * Not for trust — for capability. Browsers reserve the camera (and service
 * workers, and PWA install) for secure contexts, and a LAN IP can never
 * carry a public certificate. Self-signed and accepted once on each phone
 * is the honest LAN answer; the future VPN story (tailscale certs) replaces
 * this without changing any caller.
 *
 * Generated by the openssl every dev box and homelab already has, with the
 * current LAN IP in the SANs — and regenerated when the IP moves, since a
 * cert for yesterday's DHCP lease helps nobody.
 */

const TLS_DIR = join(ROOT, "web-tls");
const KEY_FILE = join(TLS_DIR, "key.pem");
const CERT_FILE = join(TLS_DIR, "cert.pem");
const META_FILE = join(TLS_DIR, "meta.json");

const VALID_DAYS = 3650;

type Meta = { ips: string[] };

function currentIps(): string[] {
	const ips = ["127.0.0.1"];
	const lan = lanAddress();
	if (lan) ips.unshift(lan);
	return ips;
}

function generate(ips: string[]): boolean {
	mkdirSync(TLS_DIR, { recursive: true });
	const san = ["DNS:localhost", ...ips.map((ip) => `IP:${ip}`)].join(",");
	const result = Bun.spawnSync(
		[
			"openssl", "req", "-x509", "-newkey", "ec",
			"-pkeyopt", "ec_paramgen_curve:prime256v1",
			"-keyout", KEY_FILE, "-out", CERT_FILE,
			"-days", String(VALID_DAYS), "-nodes",
			"-subj", "/CN=Toad web mode",
			"-addext", `subjectAltName=${san}`,
		],
		{ stdout: "ignore", stderr: "pipe" },
	);
	if (result.exitCode !== 0) return false;
	writeFileSync(META_FILE, `${JSON.stringify({ ips } satisfies Meta, null, 2)}\n`, "utf8");
	return true;
}

/**
 * The TLS material for the HTTPS listener, or null when openssl is missing —
 * in which case web mode still runs, plain, and the link screen falls back
 * from viewfinder to photo capture.
 */
export function ensureTls(): { key: string; cert: string } | null {
	const ips = currentIps();
	let fresh = false;
	if (!existsSync(KEY_FILE) || !existsSync(CERT_FILE)) {
		fresh = generate(ips);
		if (!fresh) return null;
	} else {
		try {
			const meta = JSON.parse(readFileSync(META_FILE, "utf8")) as Meta;
			if (!ips.every((ip) => meta.ips.includes(ip))) {
				// The address moved; each phone accepts the new cert once.
				if (!generate(ips)) return null;
			}
		} catch {
			if (!generate(ips)) return null;
		}
	}
	try {
		return { key: readFileSync(KEY_FILE, "utf8"), cert: readFileSync(CERT_FILE, "utf8") };
	} catch {
		return null;
	}
}
