import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { RoomCredential } from "../../shared/types";
import { certFingerprint } from "../node/tls";
import { ROOT } from "../paths";
import {
	createCredential,
	credentialSecret,
	deleteCredential,
	listCredentials,
	revokeCredential,
	setCredentialReplication,
} from "../store/credentials";
import { localNodeId } from "../store/records";
import { lanAddress } from "./server";

/**
 * The room's own certificate authority, and the leaf each desk serves under it.
 *
 * Not for public trust — for capability. Browsers reserve the camera (and
 * service workers, and PWA install) for secure contexts, and a LAN IP can never
 * carry a public certificate. But a *bare* self-signed leaf, which is what this
 * file used to mint, made three promises it could not keep. An MCP client had to
 * be pointed at one exact file and restarted. That file was reminted whenever
 * DHCP moved the desk, silently invalidating every client that had trusted it.
 * And a grant that names three desks meant three unrelated leaves, so a client
 * that trusted beastie broke the moment it spoke to the Mac mini.
 *
 * So the room mints one CA (the mkcert pattern): a long-lived root that signs
 * each desk's short-lived web leaf. An operator installs one certificate on a
 * client machine and every desk in the room is trusted. When an address moves,
 * only the leaf is reminted — the root is untouched, so installed trust
 * survives. That property is the whole point of this file; anything that would
 * rotate the root to fix a leaf problem is a bug.
 *
 * The CA is a replicated room record, because each desk signs its own leaf for
 * its own addresses and a desk whose CA-holder is dark must still be able to
 * remint. Certificate and private key travel together, as one sealed box per
 * desk, so no desk can hold half a root. None of that machinery is new: it is
 * `store/credentials.ts` exactly as the APNs signing key already uses it — one
 * owner, a 0600 vault on that desk, a box per member sealed to its admitted
 * Ed25519 identity, re-sealed for desks admitted later, revocation as a fact. A
 * new `ResourceKind` would have bought a second sync model, a second teardown
 * story and a second thing to get wrong; the CA is a room secret in the vault's
 * reserved `toad.` namespace instead, so it never appears in a desk's provider
 * advertisement and is never pushed into the built-in agent as an API key.
 *
 * The leaf is 825 days because that is the longest Apple will trust a locally
 * installed certificate for. The root is ten years because reissuing it is the
 * one operation that costs every client machine a visit.
 *
 * Generated by the openssl every dev box and homelab already has. No openssl,
 * no HTTPS door — web mode still runs plain, and the link screen falls back
 * from viewfinder to photo capture.
 */

const TLS_DIR = join(ROOT, "web-tls");
const KEY_FILE = join(TLS_DIR, "key.pem");
const CERT_FILE = join(TLS_DIR, "cert.pem");
const CA_FILE = join(TLS_DIR, "ca.pem");
const META_FILE = join(TLS_DIR, "meta.json");

/**
 * This desk's leaf certificate, for the listener that serves it.
 *
 * Kept as a path because the door binds from files this module owns, and
 * because a desk with no room CA still has exactly this and nothing else.
 */
export const WEB_TLS_CERT_FILE = CERT_FILE;

/**
 * The room CA certificate: the one file an operator installs on a client
 * machine, and the thing enrollment hands over.
 *
 * A phone taps through a browser warning once. An agent on another machine has
 * no such tap: it needs a file, by path, to point `NODE_EXTRA_CA_CERTS` (or its
 * language's equivalent) at. It used to be handed this desk's leaf, which meant
 * one desk's worth of trust that expired the next time DHCP moved. Now it is the
 * root, and it covers every desk in the room for as long as the room lasts.
 */
export const WEB_TLS_CA_FILE = CA_FILE;

/** The reserved provider id the room CA lives under. Never a model provider. */
export const WEB_CA_PROVIDER_ID = "toad.web-ca";

/** Ten years. Reissuing the root is the operation that costs every client a visit. */
const CA_VALID_DAYS = 3650;

/** 825 days: the longest Apple trusts a locally installed leaf. */
const LEAF_VALID_DAYS = 825;

const CA_SUBJECT = "/O=Toad/CN=Toad room CA";
const LEAF_SUBJECT = "/O=Toad/CN=Toad web mode";

/** The CA's two halves, as they sit in the vault: one JSON blob, never split. */
type CaMaterial = { cert: string; key: string };

/**
 * What the leaf on disk was minted for.
 *
 * `ca` is the fingerprint of the certificate that signed it, or null when the
 * desk is still serving a bare self-signed leaf. Both fields are remint
 * triggers: an address the leaf does not name is unreachable over HTTPS, and a
 * root the room has replaced is a leaf nobody trusts.
 */
type Meta = { ips: string[]; ca: string | null };

/** What a client has to install, and how a human checks they installed it. */
export type WebTlsTrust = {
	/** The file to trust: the room CA when there is one, else this desk's leaf. */
	path: string | null;
	/** Its SHA-256, lowercase hex — the dialect the node plane already pins in. */
	fingerprint: string | null;
	/** False while this desk is still serving a bare self-signed leaf. */
	roomCa: boolean;
};

function currentIps(): string[] {
	const ips = ["127.0.0.1"];
	const lan = lanAddress();
	if (lan) ips.unshift(lan);
	return ips;
}

/**
 * Runs one openssl invocation, and treats a missing openssl as a plain no.
 *
 * `Bun.spawnSync` throws rather than reporting an exit code when the binary is
 * not on PATH, and a throw here would take web mode down entirely on a box that
 * simply has no openssl — which is a supported way to run Toad.
 */
function openssl(args: string[]): boolean {
	try {
		return Bun.spawnSync(["openssl", ...args], { stdout: "ignore", stderr: "pipe" }).exitCode === 0;
	} catch {
		return false;
	}
}

/**
 * A private directory that exists for the length of one openssl call.
 *
 * The CA key has exactly two homes — plaintext in the owner's vault, sealed
 * everywhere else — and this file must not become a third. But openssl reads
 * and writes keys as files, so signing needs the bytes on disk for a moment.
 * `mkdtemp` makes that moment 0700 and inside the data directory rather than in
 * a world-readable temp dir, and the `finally` takes it away again.
 */
function inScratch<T>(work: (dir: string) => T | null): T | null {
	let dir: string;
	try {
		mkdirSync(TLS_DIR, { recursive: true });
		dir = mkdtempSync(join(TLS_DIR, "scratch-"));
	} catch {
		return null;
	}
	try {
		return work(dir);
	} catch {
		return null;
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}
}

/* macOS ships LibreSSL, which writes an EC key with explicit domain parameters
 * unless told otherwise. Bun's BoringSSL refuses such a key, so `Bun.serve`
 * threw at startup and the desk came up with no listener at all — silently, for
 * a day. Naming the curve makes both libraries agree, and every openssl call in
 * this file that generates a key passes it. See src/bun/node/tls.ts, which
 * learned this first. */
const EC_KEY = [
	"-newkey",
	"ec",
	"-pkeyopt",
	"ec_paramgen_curve:prime256v1",
	"-pkeyopt",
	"ec_param_enc:named_curve",
];

/**
 * A serial nobody else will pick.
 *
 * `-CAcreateserial` would start at 1 in a fresh scratch directory, so every desk
 * in the room would sign its first leaf with the same serial under the same
 * root. Sixteen random bytes with the sign bit cleared — a serial with the high
 * bit set is a negative integer, which some verifiers refuse.
 */
function serialNumber(): string {
	const bytes = randomBytes(16);
	bytes[0] = (bytes[0] as number) & 0x7f;
	return `0x${bytes.toString("hex")}`;
}

function sanList(ips: string[]): string {
	return ["DNS:localhost", ...ips.map((ip) => `IP:${ip}`)].join(",");
}

/* ------------------------------------------------------------------- the CA */

/**
 * The room's CA, minting one if the room has none this desk can see.
 *
 * Returns null when this desk holds no openable copy — not yet resealed to it,
 * or admitted after the CA was minted and the owner has not swept since. That
 * is a real state and it is handled by degrading, never by minting a second
 * root: a desk that answered a missing box with a fresh CA would give the room
 * one root per dark moment.
 */
function roomCa(): CaMaterial | null {
	try {
		const chosen = caRecord();
		if (!chosen) return mintRoomCa();
		const material = openCa(chosen);
		// Only once the winner is actually usable here: a desk that gave up its
		// own root before it could open the room's would take its clients down in
		// between, and nothing about losing a race is urgent.
		if (material) yieldTo(chosen.id);
		return material;
	} catch {
		/* A damaged vault or an unreadable store is loud on its own path. Here it
		 * means one thing: this desk has no room CA, and serves self-signed. */
		return null;
	}
}

/**
 * The room's CA record: the oldest live one, ties broken by id.
 *
 * Deliberately not `providerCredential`, which prefers the asking desk's own
 * row — the right rule for a provider key and the wrong one here, because two
 * desks would then each prefer their own root and the room would never
 * converge. This ordering is computed from replicated fields alone, so every
 * desk names the same winner from the same bytes without asking anybody.
 *
 * Two desks that mint at the same instant therefore both succeed, publish two
 * `toad.web-ca` records, and converge as soon as sync shows each the other's:
 * the older record wins, the loser's owner revokes its own row once it can open
 * the winner's, and its clients keep working on the old leaf until then. The
 * record store's own conflict rule (higher `ownerEpoch`, then higher `version`)
 * never sees this race at all — it fences edits to one record, and these are two.
 */
function caRecord(): RoomCredential | undefined {
	return listCredentials()
		.filter((credential) => credential.providerId === WEB_CA_PROVIDER_ID && !credential.revoked)
		.sort((a, b) => a.createdAt - b.createdAt || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))[0];
}

/** This desk's own copy of the CA key, opened here and now. Never written down. */
function openCa(credential: RoomCredential): CaMaterial | null {
	if (!credential.usableHere) return null;
	const blob = credentialSecret(credential.id);
	if (!blob) return null;
	try {
		const parsed = JSON.parse(blob) as Partial<CaMaterial>;
		if (!parsed.cert || !parsed.key) return null;
		// Proves the stored certificate parses before anything is signed with it.
		certFingerprint(parsed.cert);
		return { cert: parsed.cert, key: parsed.key };
	} catch {
		return null;
	}
}

/**
 * Mints the room's root and publishes it, replicated from birth.
 *
 * Replication is not the opt-in it is for a provider key. Sharing somebody's
 * Anthropic key is an operator's decision; the room CA is the room's own
 * identity, and a desk that could not remint its leaf because the root stayed on
 * one machine would be a door that goes dark the next time DHCP moves. So the
 * opt-in is made here, once, by the desk that mints.
 */
function mintRoomCa(): CaMaterial | null {
	const material = inScratch((dir) => {
		const keyFile = join(dir, "ca-key.pem");
		const certFile = join(dir, "ca-cert.pem");
		const ok = openssl([
			"req", "-x509", ...EC_KEY,
			"-keyout", keyFile, "-out", certFile,
			"-days", String(CA_VALID_DAYS), "-nodes",
			"-subj", CA_SUBJECT,
			"-addext", "basicConstraints=critical,CA:TRUE,pathlen:0",
			"-addext", "keyUsage=critical,keyCertSign,cRLSign",
			"-addext", "subjectKeyIdentifier=hash",
		]);
		if (!ok) return null;
		return { cert: readFileSync(certFile, "utf8"), key: readFileSync(keyFile, "utf8") };
	});
	if (!material) return null;
	let created: RoomCredential | undefined;
	try {
		created = createCredential({
			providerId: WEB_CA_PROVIDER_ID,
			kind: "api_key",
			label: "Toad room certificate authority",
			secret: JSON.stringify(material satisfies CaMaterial),
		});
		setCredentialReplication(created.id, true);
	} catch {
		/* A root no other desk will ever hold would make "install one certificate
		 * and the room is trusted" a lie. Better to serve self-signed and say so.
		 *
		 * Which means the two ops have to be one. Sealing is what fails here — a
		 * peer admitted with a key that will not take a box is enough — and it
		 * fails *after* the record is published, so giving up without withdrawing
		 * would leave the room a root with no boxes in it. `caRecord` names the
		 * oldest live row whatever its seals, so that row would go on winning: this
		 * desk would open it from its own vault, sign leaves under it and report a
		 * room CA, while every other desk found a root it could never open and
		 * degraded to self-signed forever. Half a mint is worse than none, so the
		 * record goes back — as a tombstone, which travels the way the record did. */
		if (created) {
			try {
				deleteCredential(created.id);
			} catch {
				/* Nothing further this desk can do. It is still refusing the root it
				 * just made, which is the part that keeps the promise honest. */
			}
		}
		return null;
	}
	return material;
}

/**
 * Revokes a losing root this desk owns, now that the winner opens here.
 *
 * Revocation rather than deletion, for the reason every other room secret is
 * revoked: the fact has to reach the desks holding a sealed copy, and
 * `revokeCredential` publishes a record with no boxes in it that does exactly
 * that. The revoked row stays in the credential list saying what happened.
 */
function yieldTo(winnerId: string): void {
	for (const credential of listCredentials()) {
		if (credential.providerId !== WEB_CA_PROVIDER_ID) continue;
		if (credential.id === winnerId || credential.revoked) continue;
		if (credential.ownerNode !== localNodeId()) continue;
		try {
			revokeCredential(credential.id);
		} catch {
			/* Somebody else's row, or one already gone. Not this desk's to force. */
		}
	}
}

/* ----------------------------------------------------------------- the leaf */

function readMeta(): Meta | null {
	try {
		const parsed = JSON.parse(readFileSync(META_FILE, "utf8")) as Partial<Meta>;
		if (!Array.isArray(parsed.ips)) return null;
		return {
			ips: parsed.ips.filter((ip): ip is string => typeof ip === "string"),
			ca: typeof parsed.ca === "string" ? parsed.ca : null,
		};
	} catch {
		return null;
	}
}

/** Whether the leaf on disk already covers these addresses under this root. */
function leafMatches(ips: string[], ca: string | null): boolean {
	if (!existsSync(KEY_FILE) || !existsSync(CERT_FILE)) return false;
	const meta = readMeta();
	if (!meta || meta.ca !== ca) return false;
	return ips.every((ip) => meta.ips.includes(ip));
}

/** Whether there is any serviceable leaf for these addresses, whoever signed it. */
function leafCovers(ips: string[]): boolean {
	if (!existsSync(KEY_FILE) || !existsSync(CERT_FILE)) return false;
	const meta = readMeta();
	return meta ? ips.every((ip) => meta.ips.includes(ip)) : false;
}

/** Puts a freshly minted pair where the listener reads it, key first and private. */
function install(key: string, cert: string, meta: Meta): void {
	mkdirSync(TLS_DIR, { recursive: true });
	// `writeFileSync`'s mode applies only when it creates the file, and a key
	// left at whatever mode a previous release wrote is a key with the wrong
	// mode forever.
	rmSync(KEY_FILE, { force: true });
	writeFileSync(KEY_FILE, key, { encoding: "utf8", mode: 0o600 });
	writeFileSync(CERT_FILE, cert, "utf8");
	writeFileSync(META_FILE, `${JSON.stringify(meta, null, 2)}\n`, "utf8");
}

/** Signs a fresh leaf for these addresses under the room's root. */
function signLeaf(ca: CaMaterial, ips: string[]): boolean {
	const done = inScratch((dir) => {
		const caCert = join(dir, "ca-cert.pem");
		const caKey = join(dir, "ca-key.pem");
		const csr = join(dir, "leaf.csr");
		const ext = join(dir, "leaf.ext");
		const keyOut = join(dir, "key.pem");
		const certOut = join(dir, "cert.pem");
		writeFileSync(caCert, ca.cert, "utf8");
		writeFileSync(caKey, ca.key, { encoding: "utf8", mode: 0o600 });
		/* Named rather than inherited from the CSR: a leaf that quietly carried
		 * whatever extensions a request asked for is how a signing key becomes a
		 * second CA. `serverAuth` is not optional either — Apple refuses a
		 * locally trusted certificate without it. */
		writeFileSync(
			ext,
			[
				"basicConstraints=critical,CA:FALSE",
				"keyUsage=critical,digitalSignature",
				"extendedKeyUsage=serverAuth",
				`subjectAltName=${sanList(ips)}`,
				"",
			].join("\n"),
			"utf8",
		);
		const requested = openssl([
			"req", "-new", ...EC_KEY,
			"-keyout", keyOut, "-out", csr, "-nodes",
			"-subj", LEAF_SUBJECT,
		]);
		if (!requested) return null;
		const signed = openssl([
			"x509", "-req", "-in", csr,
			"-CA", caCert, "-CAkey", caKey,
			"-set_serial", serialNumber(),
			"-days", String(LEAF_VALID_DAYS), "-sha256",
			"-extfile", ext, "-out", certOut,
		]);
		if (!signed) return null;
		install(readFileSync(keyOut, "utf8"), readFileSync(certOut, "utf8"), {
			ips,
			ca: certFingerprint(ca.cert),
		});
		return true;
	});
	return done === true;
}

/**
 * The old answer, kept as the honest fallback rather than as the default.
 *
 * A desk with no openable CA copy still gets a door: a phone accepts it once,
 * and an agent can still be pointed at this desk's own leaf. Going dark is the
 * failure mode this repo has already been burned by, and a bare leaf is
 * strictly more than nothing.
 */
function selfSign(ips: string[]): boolean {
	const done = inScratch((dir) => {
		const keyOut = join(dir, "key.pem");
		const certOut = join(dir, "cert.pem");
		const ok = openssl([
			"req", "-x509", ...EC_KEY,
			"-keyout", keyOut, "-out", certOut,
			"-days", String(LEAF_VALID_DAYS), "-nodes",
			"-subj", LEAF_SUBJECT,
			"-addext", `subjectAltName=${sanList(ips)}`,
		]);
		if (!ok) return null;
		install(readFileSync(keyOut, "utf8"), readFileSync(certOut, "utf8"), { ips, ca: null });
		return true;
	});
	return done === true;
}

/** Keeps the installable copy of the root beside the leaf it signed. */
function publishCa(cert: string): void {
	try {
		if (existsSync(CA_FILE) && readFileSync(CA_FILE, "utf8") === cert) return;
		mkdirSync(TLS_DIR, { recursive: true });
		writeFileSync(CA_FILE, cert, "utf8");
	} catch {
		/* The record is the authority; the file is a convenience for whoever has
		 * to install it. A desk that cannot write it still serves. */
	}
}

function load(): { key: string; cert: string } | null {
	try {
		return { key: readFileSync(KEY_FILE, "utf8"), cert: readFileSync(CERT_FILE, "utf8") };
	} catch {
		return null;
	}
}

/**
 * The TLS material for the HTTPS listener, or null when there is none to serve.
 *
 * Every path through here leaves the desk with the most trustworthy door it can
 * actually open: the room's root if it holds one, its own leaf if not, and
 * whatever was already on disk if openssl has gone missing since. Only the last
 * case answers null, and web mode then runs plain.
 */
export function ensureTls(): { key: string; cert: string } | null {
	const ips = currentIps();
	const ca = roomCa();
	if (ca) publishCa(ca.cert);
	const wanted = ca ? certFingerprint(ca.cert) : null;
	if (!leafMatches(ips, wanted)) {
		// A CA this desk holds but cannot sign against — no openssl, a toolchain
		// that refuses `-extfile` — must not cost it the leaf it already serves.
		if (!(ca && signLeaf(ca, ips)) && !leafCovers(ips)) selfSign(ips);
	}
	return load();
}

/**
 * Mints replacement material after the listener refused what it was handed.
 *
 * The node plane's `rotateNodeCert` for the web door, and the same reasoning:
 * material this process cannot serve is material no restart will fix, and it
 * survives reboots. The root is never rotated here — only the leaf — because a
 * leaf the local TLS library rejects says nothing about the root, and reissuing
 * the root would cost every client machine a visit for somebody else's bug.
 */
export function remintWebTls(): { key: string; cert: string } | null {
	const ips = currentIps();
	const ca = roomCa();
	if (ca) publishCa(ca.cert);
	if (!(ca && signLeaf(ca, ips)) && !selfSign(ips)) return null;
	return load();
}

/**
 * What a client must trust to reach this room, and how to check it did.
 *
 * The room CA when there is one — one file, every desk, surviving every address
 * change. This desk's own leaf when there is not, which is the old promise and
 * the old cost: one desk, until its address moves. The caller says which it got,
 * because "install this" and "install this, and reinstall it in a month" are
 * different instructions and an operator deserves to be told which one they are
 * following.
 *
 * A pure read of what is on disk: nothing here mints, so a surface drawing an
 * enrollment panel cannot cause a certificate to exist.
 */
export function webTlsTrust(): WebTlsTrust {
	// The root is offered only when it is the one that signed the leaf this desk
	// is actually serving. A `ca.pem` left behind by a root the room has since
	// replaced would be an install that verifies nothing, handed over with more
	// confidence than the bare leaf it replaced.
	const signedBy = readMeta()?.ca ?? null;
	if (signedBy) {
		const fingerprint = fingerprintOf(CA_FILE);
		if (fingerprint === signedBy) return { path: CA_FILE, fingerprint, roomCa: true };
	}
	const fingerprint = fingerprintOf(CERT_FILE);
	if (fingerprint) return { path: CERT_FILE, fingerprint, roomCa: false };
	return { path: null, fingerprint: null, roomCa: false };
}

/** A certificate file's SHA-256, or null — unreadable is the same as absent. */
function fingerprintOf(path: string): string | null {
	try {
		return certFingerprint(readFileSync(path, "utf8"));
	} catch {
		return null;
	}
}
