/**
 * Reading a pairing code off the desktop's screen, and working out where
 * that desktop actually is.
 *
 * Two readers, because the camera is not always available: a live
 * viewfinder in a secure context, and a capture-to-file photo everywhere
 * else. Both end at the same place — the payload of a QR, which is either
 * the `/?pair=` URL the desktop encodes or a bare code someone read out
 * loud.
 *
 * The URL carries more than the code. A native client cannot use the HTTPS
 * door the QR points at (a self-signed cert is not a thing WKWebView will
 * take on trust), so the address is rebuilt against the plain port the
 * desktop names in `?http=` — and a typed address is rebuilt the same way.
 */

/** The plain door's default, matching the bun server's own. */
const DEFAULT_HTTP_PORT = 4680;

/**
 * Pulls a pairing code out of whatever a QR carried: the /?pair= URL the
 * desktop encodes, or a bare code someone generated by other means.
 */
export function codeFromQr(text: string): string | null {
	try {
		const url = new URL(text);
		const pair = url.searchParams.get("pair");
		if (pair) return pair;
	} catch {}
	return /^[0-9a-f]{6,16}$/i.test(text.trim()) ? text.trim() : null;
}

/**
 * A code and, where the QR said so, the address to claim it at.
 *
 * `origin` is null for a bare code: it names a desktop without saying where
 * one is, so the caller has to ask. The plain door is always the one
 * returned — the https origin in the QR is for browsers, which are the only
 * clients that can accept its certificate.
 */
export function originFromPairUrl(text: string): { code: string; origin: string | null } | null {
	const trimmed = text.trim();
	try {
		const url = new URL(trimmed);
		const code = url.searchParams.get("pair");
		if (code) {
			const port = Number(url.searchParams.get("http")) || DEFAULT_HTTP_PORT;
			return { code, origin: `http://${url.hostname}:${port}` };
		}
	} catch {}
	const bare = codeFromQr(trimmed);
	return bare ? { code: bare, origin: null } : null;
}

/**
 * An address as somebody would type it, as an origin to speak to.
 *
 * A host on its own takes the default port; a scheme is accepted and forced
 * down to http, because that is the only door a native client can use.
 */
export function originFromAddress(address: string): string | null {
	const text = address.trim();
	if (!text) return null;
	// A bare host is not a URL until it has a scheme, and a typed https:// is
	// one that has to come back down to the plain door.
	const spelled = /^https?:\/\//i.test(text)
		? text.replace(/^https:/i, "http:")
		: `http://${text}`;
	let url: URL;
	try {
		url = new URL(spelled);
	} catch {
		return null;
	}
	if (!url.hostname) return null;
	return `http://${url.hostname}:${url.port || DEFAULT_HTTP_PORT}`;
}

/**
 * Decodes a QR from a photo, returning whatever the code carried.
 *
 * This is the camera path that works on plain http: getUserMedia demands a
 * secure context iOS won't grant over LAN HTTP, but a capture-to-file input
 * opens the camera anyway — the user snaps the desktop's QR and the pixels
 * are decoded right here.
 */
export async function scanPhoto(file: File): Promise<string | null> {
	const { default: jsQR } = await import("jsqr");
	const bitmap = await createImageBitmap(file);
	// Downscale for the decoder; a 12MP photo of a 220px QR is mostly air.
	const scale = Math.min(1, 1200 / Math.max(bitmap.width, bitmap.height));
	const width = Math.max(1, Math.round(bitmap.width * scale));
	const height = Math.max(1, Math.round(bitmap.height * scale));
	const canvas = document.createElement("canvas");
	canvas.width = width;
	canvas.height = height;
	const ctx = canvas.getContext("2d");
	if (!ctx) return null;
	ctx.drawImage(bitmap, 0, 0, width, height);
	const data = ctx.getImageData(0, 0, width, height);
	const hit = jsQR(data.data, width, height);
	return hit ? hit.data : null;
}

/** The same photo, read for the code alone — all the PWA needs. */
export async function codeFromPhoto(file: File): Promise<string | null> {
	const payload = await scanPhoto(file);
	return payload ? codeFromQr(payload) : null;
}

/**
 * A live viewfinder: the camera streams into the page and every ~5th frame
 * runs through the decoder until a code walks into view. Only possible in a
 * secure context — which is exactly why web mode carries an HTTPS door.
 * Returns a stop function, and calls back the moment a code is seen.
 *
 * The callback gets the payload beside the code, because a native client
 * needs the address the URL carried and the PWA does not.
 */
export async function startViewfinder(
	video: HTMLVideoElement,
	onCode: (code: string, payload: string) => void,
): Promise<() => void> {
	const { default: jsQR } = await import("jsqr");
	const stream = await navigator.mediaDevices
		.getUserMedia({ video: { facingMode: "environment", width: { ideal: 1280 } }, audio: false })
		// A laptop has no environment-facing camera; any camera beats none.
		.catch(() => navigator.mediaDevices.getUserMedia({ video: true, audio: false }));
	video.srcObject = stream;
	await video.play();

	const canvas = document.createElement("canvas");
	const ctx = canvas.getContext("2d", { willReadFrequently: true });
	let live = true;
	const stop = () => {
		live = false;
		for (const track of stream.getTracks()) track.stop();
		video.srcObject = null;
	};
	const tick = () => {
		if (!live) return;
		if (ctx && video.videoWidth > 0) {
			const scale = Math.min(1, 800 / video.videoWidth);
			canvas.width = Math.round(video.videoWidth * scale);
			canvas.height = Math.round(video.videoHeight * scale);
			ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
			const data = ctx.getImageData(0, 0, canvas.width, canvas.height);
			const hit = jsQR(data.data, canvas.width, canvas.height);
			const code = hit ? codeFromQr(hit.data) : null;
			if (code && hit) {
				stop();
				onCode(code, hit.data);
				return;
			}
		}
		setTimeout(tick, 200);
	};
	tick();
	return stop;
}
